### ISSUE TITLE
Could not load file or assembly 'System.Runtime.CompilerServices.Unsafe

### ISSUE THREAD

**Issue by myakkala-qa** [getgauge/gauge-dotnet#101]
Hi There,

I am using Microsoft.Extensions.Configuration to read the configurations from a config file, but encountering the following error message

Unhandled Exception:
System.IO.FileLoadException: Could not load file or assembly 'System.Runtime.CompilerServices.Unsafe, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
at System.Runtime.Loader.AssemblyLoadContext.LoadFromStream(IntPtr ptrNativeAssemblyLoadContext, IntPtr ptrAssemblyArray, Int32 iAssemblyArrayLen, IntPtr ptrSymbols, Int32 iSymbolArrayLen, ObjectHandleOnStack retAssembly)
at System.Runtime.Loader.AssemblyLoadContext.LoadFromStream(Stream assembly, Stream assemblySymbols)
at Gauge.Dotnet.Wrappers.AssemblyWrapper.LoadFrom(String location) 
at Gauge.Dotnet.AssemblyLoader.ScanAndLoad(String path)
at Gauge.Dotnet.AssemblyLoader..ctor(IAssemblyWrapper assemblyWrapper, IEnumerable`1 assemblyLocations, IReflectionWrapper reflectionWrapper, IActivatorWrapper activatorWrapper, IStepRegistry registry) 
at Gauge.Dotnet.GaugeListener.StartServer()
at Gauge.Dotnet.StartCommand.Execute()
at Gauge.Dotnet.Program.Main(String[] args)
Error occurred while waiting for runner process to finish.

Thanks,
Mani

**Comment by sriv** [comment]
hi - can you share a sample project for us to replicate this? that would also help confirm that whatever we change would fix this.

**Comment by NivedhaSenthil** [comment]
@myakkala-qa any updates ?

**Comment by myakkala-qa** [comment]
Hi There,

I just created a sample project and added Microsoft.Extensions.Configuration package to the project. After that when I run a example scenario the reported error message is encountered.
[TestGuage.zip](https://github.com/getgauge/gauge-dotnet/files/5117255/TestGuage.zip)

Please do let me know for further information.

Thanks,
Mani

**Comment by sriv** [comment]
should be fixed via #106 and released as part of gauge-dotnet v0.1.6. Closing this, please comment if this is still an issue.
