### ISSUE TITLE
Sequence contains no matching element error while running

### ISSUE THREAD

**Issue by preetipadalia** [getgauge/gauge-dotnet#113]
Hi,

I am trying to run the project but getting following error.
Error Message: Sequence contains no matching element
Stacktrace:
at System.Linq.ThrowHelper.ThrowNoMatchException()
at System.Linq.Enumerable.First[TSource](IEnumerable1 source, Func2 predicate)
at Gauge.Dotnet.AssemblyLoader.GetLibType(LibType type)
at Gauge.Dotnet.ExecutionOrchestrator.GetAllPendingScreenshotFiles()
at Gauge.Dotnet.ExecutionOrchestrator.BuildResult(Stopwatch stopwatch, ExecutionResult executionResult)
at Gauge.Dotnet.ExecutionOrchestrator.ExecuteHooks(String hookType, HooksStrategy strategy, IList1 applicableTags, ExecutionContext context) at Gauge.Dotnet.Processors.HookExecutionProcessor.ExecuteHooks(ExecutionInfo info) at Gauge.Dotnet.Processors.ExecutionEndingProcessor.Process(ExecutionEndingRequest request) at Gauge.Dotnet.RunnerServiceHandler.<>c__DisplayClass29_0.<FinishExecution>b__0() at Gauge.Dotnet.RunnerServiceHandler.processAndGetTask[TResult](Func1 fn)

 While debugging I found following line in gauge-dotnet causing the issue in following method:
ProtoExecutionResult BuildResult(Stopwatch stopwatch, ExecutionResult executionResult)
           // var allPendingScreenShotFiles = GetAllPendingScreenshotFiles().Where(s => s != null);
           // result.ScreenshotFiles.AddRange(allPendingScreenShotFiles);

and 
 protected virtual ExecutionStatusResponse ExecuteHooks(ExecutionInfo info)
        {
            var applicableTags = GetApplicableTags(info);
            var protoExecutionResult =
                ExecutionOrchestrator.ExecuteHooks(HookType, Strategy, applicableTags, info);
            var allPendingMessages = ExecutionOrchestrator.GetAllPendingMessages().Where(m => m != null);
           // var allPendingScreenShotFiles = ExecutionOrchestrator.GetAllPendingScreenshotFiles();
            protoExecutionResult.Message.AddRange(allPendingMessages);
            //protoExecutionResult.ScreenshotFiles.AddRange(allPendingScreenShotFiles);
            return new ExecutionStatusResponse { ExecutionResult = protoExecutionResult };
        }

I have commented the lines and then tried it worked. Can you please guide me on what can be wrong. 

Gauge version: 1.1.3
Commit Hash: 9d3a3d5

Plugins
-------
dotnet (0.1.7)
html-report (4.0.8)
screenshot (0.0.1)

**Comment by sriv** [comment]
What is the version of `Gauge.CSharp.Lib` in your project?

**Comment by preetipadalia** [comment]
its 0.7.3.

**Comment by sriv** [comment]
Can you upgrade it to the latest (https://www.nuget.org/packages/Gauge.CSharp.Lib/0.7.8) ?

**Comment by preetipadalia** [comment]
After Upgrading it started working thanks.

**Comment by sriv** [comment]
reopening = gauge-dotnet should handle this better.
