### ISSUE TITLE
FileLoadException when System.Data.SqlClient is included to gauge-dotnet .csproj file.

### ISSUE THREAD

**Issue by gemunulk** [getgauge/gauge-dotnet#34]
### Expected behavior
Gauge dotnet project should work with [System.Data.SqlClient](https://docs.microsoft.com/en-us/dotnet/api/system.data.sqlclient?view=netcore-2.1)

### Actual behavior
` Failed to initialize suite datastore. Error: Connection closed [127.0.0.1:52720] cause: EOF
Gauge.Dotnet.GaugeListener System.IO.FileLoadException: Could not load file or assembly 'System.Runtime.CompilerServices.Unsafe, Version=4.0.4.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromStream(IntPtr ptrNativeAssemblyLoadContext, IntPtr ptrAssemblyArray, Int32 iAssemblyArrayLen, IntPtr ptrSymbols, Int32 iSymbolArrayLen, ObjectHandleOnStack retAssembly)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromStream(Stream assembly, Stream assemblySymbols)
   at Gauge.Dotnet.Wrappers.AssemblyWrapper.LoadFrom(String location) in /Users/vagrant/go-agent-17.4.0/pipelines/dotnet-package/src/Wrappers/AssemblyWrapper.cs:line 42
   at Gauge.Dotnet.AssemblyLoader.ScanAndLoad(String path) in /Users/vagrant/go-agent-17.4.0/pipelines/dotnet-package/src/AssemblyLoader.cs:line 128
   at Gauge.Dotnet.AssemblyLoader..ctor(IAssemblyWrapper assemblyWrapper, IEnumerable1 assemblyLocations, IReflectionWrapper reflectionWrapper) in /Users/vagrant/go-agent-17.4.0/pipelines/dotnet-package/src/AssemblyLoader.cs:line 43
   at Gauge.Dotnet.MessageProcessorFactory.GetProcessor(MessageType messageType, Boolean scan) in /Users/vagrant/go-agent-17.4.0/pipelines/dotnet-package/src/MessageProcessorFactory.cs:line 50
   at Gauge.Dotnet.GaugeListener.PollForMessages() in /Users/vagrant/go-agent-17.4.0/pipelines/dotnet-package/src/GaugeListener.cs:line 56`
### Steps to replicate

1. gauge init dotnet
2. Include  `<PackageReference Include="System.Data.SqlClient" Version="4.6.0" />` in to the netcore-template.csproj
3.  gauge run specs/

### Version
Platform: Windows 10
Dotent Version: Microsoft .NET Core SDK 2.1.402 
Gauge version: 1.0.3
Commit Hash: ff6c0c3

### Plugins
dotnet (0.1.0)

**Comment by negiDharmendra** [comment]
@gemunulk  I am not familiar with .Net eco system. Following reads might help you to resolve the issue. 

https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/redirect-assembly-versions

https://github.com/dotnet/corefx/issues/30631

**Comment by nehashri** [comment]
please reopen the issue if you have any other concerns
