### ISSUE TITLE
  Failed to initialize suite datastore. Error: Connection closed [127.0.0.1:59020] cause: EOF

### ISSUE THREAD

**Issue by pp1609** [getgauge/gauge-dotnet#45]
Hi,

I am trying to run gauge test in .netcoreapp3.0 but not able to proceed as getting following error:

Failed to initialize suite datastore. Error: Connection closed [127.0.0.1:59020] cause: EOF

Gauge.Dotnet.GaugeListener System.IO.FileLoadException: Could not load file or assembly 'Microsoft.CodeAnalysis.CSharp, Version=3.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromStream(IntPtr ptrNativeAssemblyLoadContext, IntPtr ptrAssemblyArray, Int32 iAssemblyArrayLen, IntPtr ptrSymbols, Int32 iSymbolArrayLen, ObjectHandleOnStack retAssembly)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromStream(Stream assembly, Stream assemblySymbols)
   at Gauge.Dotnet.Wrappers.AssemblyWrapper.LoadFrom(String location) in /Users/vagrant/go-agent-17.4.0/pipelines/dotnet-package/src/Wrappers/AssemblyWrapper.cs:line 43
   at Gauge.Dotnet.AssemblyLoader.ScanAndLoad(String path) in /Users/vagrant/go-agent-17.4.0/pipelines/dotnet-package/src/AssemblyLoader.cs:line 128
   at Gauge.Dotnet.AssemblyLoader..ctor(IAssemblyWrapper assemblyWrapper, IEnumerable`1 assemblyLocations, IReflectionWrapper reflectionWrapper) in /Users/vagrant/go-agent-17.4.0/pipelines/dotnet-package/src/AssemblyLoader.cs:line 43
   at Gauge.Dotnet.MessageProcessorFactory.GetProcessor(MessageType messageType, Boolean scan) in /Users/vagrant/go-agent-17.4.0/pipelines/dotnet-package/src/MessageProcessorFactory.cs:line 50
   at Gauge.Dotnet.GaugeListener.PollForMessages() in /Users/vagrant/go-agent-17.4.0/pipelines/dotnet-package/src/GaugeListener.cs:line 56
Specifications:	0 executed	0 passed	0 failed	0 skipped
Scenarios:	0 executed	0 passed	0 failed	0 skipped

Total time taken: 718ms
Success: Tests passed.

Kindly help.

**Comment by shubhamsc** [comment]
@pp1609 There was a similar issue. Refer #36
Check the comments, might help you to resolve the issue.

**Comment by BugDiver** [comment]
@pp1609 The .Net Core 3.0 is not officially released yet. Are trying to use Gauge with Dotnet `preview` version?

**Comment by pp1609** [comment]
I found the reason of the issue. The issue was appearing when i was referencing some other project in gauge project.

**Comment by luciferankon** [comment]
@pp1609 Hey is the issue resoved?

**Comment by nehashri** [comment]
@pp1609 Please reopen the issue if you are still facing this.
