### ISSUE TITLE
An exception of type 'System.ArgumentNullException' occurred in System.Private.CoreLib.dll but was not handled in user code: 'Value cannot be null.'

### ISSUE THREAD

**Issue by pp1609** [getgauge/gauge-dotnet#48]
Hi,

I am trying to add extent report core package in gauge project. The same package is working fine in console/Nunit .netcoreapp2.2 project but in gauge the exception is throwing as soon as reporter is getting attached.
 at System.IO.StreamReader..ctor(Stream stream, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean leaveOpen)
   at AventStack.ExtentReports.Reporter.TemplateEngine.TemplateLoadService.LoadTemplate[T](String[] templates)

Kindly help.

**Comment by Apoorva-GA** [comment]
@pp1609 Could you give us more info so that it will be helpful for us to debug the issue.
- OS information
- Run `gauge -v` and paste the result
- Steps to reproduce the issue.

**Comment by nehashri** [comment]
@pp1609 Can you please provide more details as mentioned by @Apoorva-GA

**Comment by shubhamsc** [comment]
Closing this issue due to inactivity. Please feel free to reopen this if you still getting the same error.
