### ISSUE TITLE
System.Data.SqlClient & Microsoft.Data.SqlClient PlatformNotSupportedException

### ISSUE THREAD

**Issue by sustundag** [getgauge/gauge-dotnet#80]
Hi,

I have to execute crud queries on sql server to prepare test data before and after specs.
But I am getting **PlatformNotSupportedException**.

_ps: Development environment windows 10, Visual Studio Code_
To reproduce the exception;

**Scenario A:**

1) I have created a new template project with gauge init dotnet and run the specs. Everything was ok.
Versions:
**_Project:_**
TargetFramework:netstandard2.0
PackageReference Include="FluentAssertions" Version="4.19.4"
PackageReference Include="Gauge.CSharp.Lib" Version="0.7.6"
**_Gauge:_**
Gauge version: 1.0.8
Commit Hash: 28617ea
Plugins:
csharp (0.10.6)
dotnet (0.1.4)
flash (0.0.2)
html-report (4.0.10)
json-report (0.3.3)
screenshot (0.0.1)
spectacle (0.1.4)
xml-report (0.2.3)

gauge update -c
No Updates available.

2) Added EntityFrameworkCore.SqlServer Package 2.2.6 and run again the specs. Everything was ok.
PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="2.2.6"
Package dependencies:
.NETStandard 2.0
Microsoft.EntityFrameworkCore.Relational (>= 2.2.6)
System.Data.SqlClient (>= 4.6.1)

3) Added Sqlconnection code to SetLanguageVowels method and run again.
```
public void SetLanguageVowels(string vowelString)
        {
            SqlConnection sql=new SqlConnection("blablabal");
```

I got exception below:
Error Message: System.Data.SqlClient is not supported on this platform.
        Stacktrace: 
           at System.Data.SqlClient.SqlConnection..ctor(String connectionString)
           at netcore.template.StepImplementation.SetLanguageVowels(String vowelString) in c:\Users\serkan.ustundag\source\repos\GaugeSqlClientIssue\StepImplementation.cs:line 18

Scenario B:
1) I made some search and decided to test .netstandard 2.1, gauge.charp.lib 0.7.8 and entityframework 3.3.1
**_Project:_**
TargetFramework:netstandard2.1
PackageReference Include="FluentAssertions" Version="4.19.4"
PackageReference Include="Gauge.CSharp.Lib" Version="0.7.8"
PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="3.1.3"
**_Gauge:_**
Gauge version: 1.0.8
Commit Hash: 28617ea
Plugins:
csharp (0.10.6)
dotnet (0.1.4)
flash (0.0.2)
html-report (4.0.10)
json-report (0.3.3)
screenshot (0.0.1)
spectacle (0.1.4)
xml-report (0.2.3)

gauge update -c
No Updates available.

2) entityframework 3.3.1  dependencies
.NETStandard 2.0
Microsoft.Data.SqlClient (>= 1.0.19269.1)
Microsoft.EntityFrameworkCore.Relational (>= 3.1.3)

2) Run again and got exception below
 Error Message: Microsoft.Data.SqlClient is not supported on this platform.
        Stacktrace: 
           at Microsoft.Data.SqlClient.SqlConnection..ctor(String connectionString)
           at netcore.template.StepImplementation.SetLanguageVowels(String vowelString) in c:\Users\serkan.ustundag\source\repos\GaugeSqlClientIssue\StepImplementation.cs:line 18

Last, I downgraded Entityframework.sqlserver version to 2.2.6 and 3.0.3
Unfortunately nothing changed. I got "Microsoft.Data.SqlClient is not supported on this platform" or "System.Data.SqlClient is not supported on this platform" depends on tested version.

Thanks
Serkan

**Comment by 82949712** [comment]
same issue here

**Comment by sriv** [comment]
I can see this issue as well. 

While Gauge does not deal with any database related libraries, in this case what's happening is that the Assemblies referenced are loaded using ApplicationLoadContext.Default.LoadAssemblyFromStream - and this is causing this error (for reasons yet unknown to me). This issue seems related: https://github.com/dotnet/runtime/issues/27899

As far as gauge-dotnet is concerned, I could see that the assemblies are referenced and are being loaded. However the runtime does not recognize it properly.

**Comment by sriv** [comment]
After some headbanging, I discovered that `Microsoft.Data.SqlClient` has this check - https://github.com/dotnet/SqlClient/blob/9e13645313d69e783998de47ada0ec186b0d3f9e/src/Microsoft.Data.SqlClient/netcore/src/Microsoft.Data.SqlClient.csproj#L5

Which looks at the targetOS of the project built and it has to be a valid runtime id (Ref: https://docs.microsoft.com/en-us/dotnet/core/rid-catalog)

Basically, this will require `--runtime=<>` to be passed to the `dotnet publish` command. Gauge-dotnet does not [do this](https://github.com/getgauge/gauge-dotnet/blob/master/src/GaugeProjectBuilder.cs#L32), since there is no need for gauge's features to work.

So the options are:

- use `dotnet publish` with `--runtime` to build the project. set the output location as `GAUGE_CUSTOM_BUILD_PATH` [Recommended]

- if you still with to let gauge do the build, there is a hack - there is a env variable `GAUGE_CSHARP_PROJECT_CONFIG` which gauge-dotnet uses to let projects decide what args be passed to `--configuration`. You can piggyback on this and append the `--runtime=<>` and this will be picked up while building the project.

Note - post setting `--runtime` I see an expected error now:

```
$ gauge run specs
Microsoft (R) Build Engine version 16.4.0+e901037fe for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.
# Specification Heading
  ## Vowel counts in single word	 ✘
        Failed Step: Vowels in English language are "aeiou".
        Specification: specs/example.spec:11
        Error Message: Format of the initialization string does not conform to specification starting at index 0.
        Stacktrace: 
           at Microsoft.Data.Common.DbConnectionOptions.GetKeyValuePair(String connectionString, Int32 currentPosition, StringBuilder buffer, Boolean useOdbcRules, String& keyname, String& keyvalue)
           at Microsoft.Data.Common.DbConnectionOptions.ParseInternal(Dictionary`2 parsetable, String connectionString, Boolean buildChain, Dictionary`2 synonyms, Boolean firstKey)
           at Microsoft.Data.Common.DbConnectionOptions..ctor(String connectionString, Dictionary`2 synonyms)
           at Microsoft.Data.SqlClient.SqlConnectionString..ctor(String connectionString)
           at Microsoft.Data.SqlClient.SqlConnectionFactory.CreateConnectionOptions(String connectionString, DbConnectionOptions previous)
           at Microsoft.Data.ProviderBase.DbConnectionFactory.GetConnectionPoolGroup(DbConnectionPoolKey key, DbConnectionPoolGroupOptions poolOptions, DbConnectionOptions& userConnectionOptions)
           at Microsoft.Data.SqlClient.SqlConnection.ConnectionString_Set(DbConnectionPoolKey key)
           at Microsoft.Data.SqlClient.SqlConnection.set_ConnectionString(String value)
           at netcore.template.StepImplementation.SetLanguageVowels(String vowelString) in /tmp/bar/StepImplementation.cs:line 19
```
